name: Run News Crawler

on:
  # schedule:
  #   - cron: '0 13 * * *'
  workflow_dispatch:  # Allows manual triggers

jobs:
  crawl:
    environment: crawler

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install Playwright
      run: |
        python -m pip install --upgrade pip
        pip install playwright
        playwright install chromium
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Setup Firebase credentials
      env:
        FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
      run: |
        echo "${FIREBASE_CONFIG}" > firebase-config.json
        # Verify JSON is valid
        python -c "import json; json.load(open('firebase-config.json'))"
        
    - name: Setup Environment Variables
      run: |
        echo "ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}" >> $GITHUB_ENV
        echo "FIREBASE_CONFIG_PATH=firebase-config.json" >> $GITHUB_ENV
        echo "FIREBASE_DEFAULT_DATABASE_URL=${{ secrets.FIREBASE_DEFAULT_DATABASE_URL }}" >> $GITHUB_ENV
        
    - name: Run crawler
      run: python python/crawlers/Celebrity_news_crawler.py
